<a href="https://colab.research.google.com/github/sumedhakoranga/Logic_Gates_Neural_Networks/blob/main/AND_Gate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Initialization

In [2]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import random

# Generating synthetic data

In [3]:
p0 = [[0, 0,0] for _ in range(random.randint(100, 150))]
p1 = [[0,1,1] for _ in range(random.randint(100, 150))]
p2 = [[1,0,1] for _ in range(random.randint(100, 150))]
p3 = [[1,1,1] for _ in range(random.randint(100, 150))]
X = np.array(p0+p1+p2+p3)
np.random.shuffle(X)
y = X[:, 1]
X = X[:, :2]

In [4]:
X

array([[0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [0, 1],
       [1, 1],
       [0, 1],
       [1, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 1],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 0],
       [1, 1],
       [0, 1],
       [1, 0],
       [1, 1],
       [0, 1],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [0,

In [5]:
y

array([1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,

# Training the model

In [6]:
model = keras.Sequential([
    keras.Input(shape=(2)),
    keras.layers.Dense(1,activation="sigmoid")]
)

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 3         
                                                                 
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics='accuracy')

In [9]:
model.fit(X,y,epochs=1000,batch_size=32)

Epoch 1/1000
15/15 [==============================] - 1s 2ms/step - loss: 1.0689 - accuracy: 0.2574
Epoch 2/1000
15/15 [==============================] - 0s 1ms/step - loss: 1.0580 - accuracy: 0.2363
Epoch 3/1000
15/15 [==============================] - 0s 1ms/step - loss: 1.0477 - accuracy: 0.2363
Epoch 4/1000
15/15 [==============================] - 0s 2ms/step - loss: 1.0371 - accuracy: 0.2363
Epoch 5/1000
15/15 [==============================] - 0s 2ms/step - loss: 1.0271 - accuracy: 0.2363
Epoch 6/1000
15/15 [==============================] - 0s 2ms/step - loss: 1.0178 - accuracy: 0.2363
Epoch 7/1000
15/15 [==============================] - 0s 2ms/step - loss: 1.0083 - accuracy: 0.2363
Epoch 8/1000
15/15 [==============================] - 0s 1ms/step - loss: 0.9989 - accuracy: 0.2363
Epoch 9/1000
15/15 [==============================] - 0s 1ms/step - loss: 0.9902 - accuracy: 0.2363
Epoch 10/1000
15/15 [==============================] - 0s 1ms/step - loss: 0.9812 - accuracy: 0.2363

In [10]:
model.get_weights()

[array([[-0.14662236],
        [ 9.335224  ]], dtype=float32),
 array([-4.394254], dtype=float32)]

In [11]:
model.get_weight_paths()

{'dense.kernel': <tf.Variable 'dense/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[-0.14662236],
        [ 9.335224  ]], dtype=float32)>,
 'dense.bias': <tf.Variable 'dense/bias:0' shape=(1,) dtype=float32, numpy=array([-4.394254], dtype=float32)>}