<a href="https://colab.research.google.com/github/sumedhakoranga/Logic_Gates_Neural_Networks/blob/main/OR_Gate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Initialization

In [9]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import random

# Generating synthetic data

In [10]:
p0 = [[0, 0,0] for _ in range(random.randint(100, 150))]
p1 = [[0,1,0] for _ in range(random.randint(100, 150))]
p2 = [[1,0,0] for _ in range(random.randint(100, 150))]
p3 = [[1,1,1] for _ in range(random.randint(100, 150))]
X = np.array(p0+p1+p2+p3)
np.random.shuffle(X)
y = X[:, 1]
X = X[:, :2]

In [11]:
X

array([[0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 1],
       [0, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 0],
       [1, 1],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [1, 1],
       [0, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 1],
       [1, 0],
       [0, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [1, 1],
       [0, 1],
       [1, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 1],
       [0, 1],
       [0, 0],
       [0, 1],
       [1, 0],
       [0, 0],
       [0, 1],
       [1,

In [12]:
y

array([0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,

# Training the model

In [13]:
model = keras.Sequential([
    keras.Input(shape=(2)),
    keras.layers.Dense(1,activation="sigmoid")]
)

In [14]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [15]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics='accuracy')

In [16]:
model.fit(X,y,epochs=1000,batch_size=32)

Epoch 1/1000
15/15 [==============================] - 1s 1ms/step - loss: 0.4764 - accuracy: 0.7857
Epoch 2/1000
15/15 [==============================] - 0s 1ms/step - loss: 0.4729 - accuracy: 1.0000
Epoch 3/1000
15/15 [==============================] - 0s 1ms/step - loss: 0.4695 - accuracy: 1.0000
Epoch 4/1000
15/15 [==============================] - 0s 1ms/step - loss: 0.4660 - accuracy: 1.0000
Epoch 5/1000
15/15 [==============================] - 0s 994us/step - loss: 0.4628 - accuracy: 1.0000
Epoch 6/1000
15/15 [==============================] - 0s 1ms/step - loss: 0.4594 - accuracy: 1.0000
Epoch 7/1000
15/15 [==============================] - 0s 1ms/step - loss: 0.4562 - accuracy: 1.0000
Epoch 8/1000
15/15 [==============================] - 0s 2ms/step - loss: 0.4530 - accuracy: 1.0000
Epoch 9/1000
15/15 [==============================] - 0s 1ms/step - loss: 0.4500 - accuracy: 1.0000
Epoch 10/1000
15/15 [==============================] - 0s 1ms/step - loss: 0.4469 - accuracy: 1.00

In [17]:
model.get_weights()

[array([[-0.23508196],
        [11.255689  ]], dtype=float32),
 array([-5.304128], dtype=float32)]

In [18]:
model.get_weight_paths()

{'dense_1.kernel': <tf.Variable 'dense_1/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[-0.23508196],
        [11.255689  ]], dtype=float32)>,
 'dense_1.bias': <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([-5.304128], dtype=float32)>}