<a href="https://colab.research.google.com/github/sumedhakoranga/Logic_Gates_Neural_Networks/blob/main/XNOR_Gate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Initialization

In [6]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import random

# Generating synthetic data

In [7]:
p0 = [[0, 0,1] for _ in range(random.randint(100, 150))]
p1 = [[0,1,0] for _ in range(random.randint(100, 150))]
p2 = [[1,0,0] for _ in range(random.randint(100, 150))]
p3 = [[1,1,1] for _ in range(random.randint(100, 150))]
X = np.array(p0+p1+p2+p3)
np.random.shuffle(X)
y = X[:, 1]
X = X[:, :2]

In [8]:
X

array([[1, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 0],
       [0, 0],
       [1, 1],
       [1, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 1],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 0],
       [1, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 1],
       [0, 0],
       [0, 1],
       [1, 1],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0,

In [9]:
y

array([0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,

# Training the model

In [16]:
model = keras.Sequential([
    keras.Input(shape=(2)),
    keras.layers.Dense(2,activation="sigmoid"),
    keras.layers.Dense(1,activation="sigmoid")]
)

In [17]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 2)                 6         
                                                                 
 dense_2 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics='accuracy')

In [19]:
model.fit(X,y,epochs=1000,batch_size=32)

Epoch 1/1000
15/15 [==============================] - 1s 3ms/step - loss: 0.6773 - accuracy: 0.6842
Epoch 2/1000
15/15 [==============================] - 0s 3ms/step - loss: 0.6762 - accuracy: 0.7200
Epoch 3/1000
15/15 [==============================] - 0s 2ms/step - loss: 0.6751 - accuracy: 0.7200
Epoch 4/1000
15/15 [==============================] - 0s 2ms/step - loss: 0.6740 - accuracy: 0.7200
Epoch 5/1000
15/15 [==============================] - 0s 2ms/step - loss: 0.6729 - accuracy: 0.7200
Epoch 6/1000
15/15 [==============================] - 0s 2ms/step - loss: 0.6717 - accuracy: 0.7200
Epoch 7/1000
15/15 [==============================] - 0s 2ms/step - loss: 0.6706 - accuracy: 0.7200
Epoch 8/1000
15/15 [==============================] - 0s 2ms/step - loss: 0.6695 - accuracy: 0.7200
Epoch 9/1000
15/15 [==============================] - 0s 3ms/step - loss: 0.6682 - accuracy: 0.7200
Epoch 10/1000
15/15 [==============================] - 0s 2ms/step - loss: 0.6669 - accuracy: 0.7200

In [20]:
model.get_weights()

[array([[ 0.05109422, -0.05123981],
        [-7.0921583 ,  7.227747  ]], dtype=float32),
 array([ 3.4112265, -3.479132 ], dtype=float32),
 array([[-8.300057],
        [ 8.189827]], dtype=float32),
 array([0.01820502], dtype=float32)]

In [21]:
model.get_weight_paths()

{'dense_1.kernel': <tf.Variable 'dense_1/kernel:0' shape=(2, 2) dtype=float32, numpy=
 array([[ 0.05109422, -0.05123981],
        [-7.0921583 ,  7.227747  ]], dtype=float32)>,
 'dense_1.bias': <tf.Variable 'dense_1/bias:0' shape=(2,) dtype=float32, numpy=array([ 3.4112265, -3.479132 ], dtype=float32)>,
 'dense_2.kernel': <tf.Variable 'dense_2/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[-8.300057],
        [ 8.189827]], dtype=float32)>,
 'dense_2.bias': <tf.Variable 'dense_2/bias:0' shape=(1,) dtype=float32, numpy=array([0.01820502], dtype=float32)>}