<a href="https://colab.research.google.com/github/sumedhakoranga/Logic_Gates_Neural_Networks/blob/main/XOR_Gate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Initialization

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import random

# Generating synthetic data

In [ ]:
p0 = [[0, 0, 0] for _ in range(random.randint(100, 150))]
p1 = [[0,1,1] for _ in range(random.randint(100, 150))]
p2 = [[1,0,1] for _ in range(random.randint(100, 150))]
p3 = [[1,1,0] for _ in range(random.randint(100, 150))]
X = np.array(p0+p1+p2+p3)
np.random.shuffle(X)
y = X[:, 2]
X = X[:, :2]

In [ ]:
X

array([[0, 1],
       [0, 1],
       [1, 0],
       ...,
       [1, 0],
       [1, 0],
       [0, 0]])

In [ ]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,

# Training the model

In [ ]:
model = keras.Sequential([
    keras.Input(shape=(2)),
    keras.layers.Dense(2,activation="sigmoid"),
    keras.layers.Dense(1,activation="sigmoid")]
)

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 2)                 6         
                                                                 
 dense_3 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics='accuracy')

In [ ]:
model.fit(X,y,epochs=1000,batch_size=32)

Epoch 1/1000
16/16 [==============================] - 1s 2ms/step - loss: 0.7910 - accuracy: 0.4579
Epoch 2/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.7832 - accuracy: 0.4579
Epoch 3/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.7759 - accuracy: 0.4579
Epoch 4/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.7685 - accuracy: 0.4579
Epoch 5/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.7620 - accuracy: 0.4579
Epoch 6/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.7556 - accuracy: 0.4579
Epoch 7/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.7496 - accuracy: 0.4579
Epoch 8/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.7440 - accuracy: 0.4579
Epoch 9/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.7387 - accuracy: 0.4579
Epoch 10/1000
16/16 [==============================] - 0s 2ms/step - loss: 0.7338 - accuracy: 0.4579

In [ ]:
model.get_weights()

[array([[-8.640526,  9.936205],
        [12.19848 , 11.800795]], dtype=float32),
 array([ 4.454284, -3.951037], dtype=float32),
 array([[-3.8283694],
        [ 3.9820979]], dtype=float32),
 array([-0.31022668], dtype=float32)]

In [ ]:
model.get_weight_paths()

{'dense_2.kernel': <tf.Variable 'dense_2/kernel:0' shape=(2, 2) dtype=float32, numpy=
 array([[-8.640526,  9.936205],
        [12.19848 , 11.800795]], dtype=float32)>,
 'dense_2.bias': <tf.Variable 'dense_2/bias:0' shape=(2,) dtype=float32, numpy=array([ 4.454284, -3.951037], dtype=float32)>,
 'dense_3.kernel': <tf.Variable 'dense_3/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[-3.8283694],
        [ 3.9820979]], dtype=float32)>,
 'dense_3.bias': <tf.Variable 'dense_3/bias:0' shape=(1,) dtype=float32, numpy=array([-0.31022668], dtype=float32)>}